# Generated by Django 3.2.8 on 2022-03-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual'), ('No recurrente', 'No Recurrente')], default='Mensual', max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(blank=True)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Alimentación', 'Alimentacion'), ('Hogar', 'Hogar'), ('Entretenimiento', 'Entretenimiento'), ('Educación', 'Educacion'), ('Compromisos Bancarios', 'Compromisos Bancarios'), ('Otros', 'Otros')], default='Otros', max_length=30)),
                ('recurrencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual'), ('No recurente', 'No Recurrente')], default='Mensual', max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(blank=True)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
                ('factura', models.ImageField(upload_to='images')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
