# Generated by Django 3.2.8 on 2022-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gastos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='factura',
            field=models.ImageField(blank=True, upload_to='app/images/'),
        ),
    ]
