# Generated by Django 3.2.8 on 2022-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
